# Generated by Django 5.2.14 on 2026-05-18 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True, default='')),
                ('applied_platform', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Naukri', 'Naukri'), ('Indeed', 'Indeed'), ('Wellfound', 'Wellfound'), ('Internshala', 'Internshala'), ('Foundit', 'Foundit'), ('Company Website', 'Company Website'), ('Referral', 'Referral'), ('Other', 'Other')], default='Other', max_length=50)),
                ('job_url', models.URLField(blank=True, default='', max_length=500)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('applied_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview Scheduled', 'Interview Scheduled'), ('HR Round', 'HR Round'), ('Rejected', 'Rejected'), ('Offer Received', 'Offer Received'), ('Joined', 'Joined')], default='Applied', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_16fc9d_idx'), models.Index(fields=['user', 'applied_platform'], name='application_user_id_0e8dd1_idx'), models.Index(fields=['user', 'applied_date'], name='application_user_id_42b6ac_idx')],
            },
        ),
    ]
