# Generated by Django 5.2.14 on 2026-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_platform',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Naukri', 'Naukri'), ('Indeed', 'Indeed'), ('Wellfound', 'Wellfound'), ('Internshala', 'Internshala'), ('Foundit', 'Foundit'), ('Company Website', 'Company Website'), ('Referral', 'Referral'), ('Naresh IT Placement Cell', 'Naresh IT Placement Cell'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
